version: '3'
services:
    postgres_db:
        image: postgres
        networks:
            - custom_net
        volumes:
            - pg_db:/data
        environment:
            - POSTGRES_USER:     ${PG_USER}
              POSTGRES_PASSWORD: ${PG_PASS}

    mongo_db:
        image: mongo_db
        volumes:
            - mongo_db:/data
        networks:
            - custom_net
        environment:
            -  MONGO_INITDB_ROOT_USERNAME: "${MONGO_USER}"
               MONGO_INITDB_ROOT_PASSWORD: "${MONGO_PASS}"

    asp_net:
        build: net_app/TaskApplicationAPI/TaskApplicationAPI/.
        networks: 
            - custom_net

